[workspace]
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
python = "3.11.*"
pydantic = ">=2.8,<3"
pytest = ">=8.2,<9"
pyyaml = ">=6,<7"
jsonschema = ">=4.23,<5"

[tasks]
demo = "python main.py"
test = "pytest"
