"""Frozen-config I/O: a strict YAML subset for ``RetrievalConfig`` (4.3 / AGENTS).

AGENTS.md requires version numbers and thresholds to live in ``config/`` or
versioned assets.  ``RetrievalConfig`` remains the in-code validated source of
truth; this module writes a canonical YAML copy and reloads it with a *strict,
stdlib-only* parser that rejects every construct the writer cannot produce —
unknown keys, unknown value kinds, and malformed structure fail loudly instead
of being silently ignored.

Supported YAML subset (exactly what ``write_config_yaml`` emits):

- ``#`` comment lines and blank lines
- nested mappings by two-space indentation (``key: value`` / ``key:``)
- sequences of flow scalars (``- item``)
- inline flow sequences of scalars (``[a, b]``)
- plain scalars: integers, floats, true/false, null, and strings

Anything else (anchors, multi-line strings, quoted strings, nested flow maps)
raises ``ConfigYamlError``.
"""

from __future__ import annotations

from dataclasses import fields
from pathlib import Path
from typing import Any

from .config import FeatureWeights, RetrievalConfig


class ConfigYamlError(ValueError):
    """Raised when a config YAML file is malformed or mismatched."""


def write_config_yaml(path: str | Path, config: RetrievalConfig) -> Path:
    """Serialize ``config`` to the canonical frozen YAML and return its path."""
    if not isinstance(config, RetrievalConfig):
        raise ValueError("config must be a RetrievalConfig")
    config.__post_init__()
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Frozen A4 retrieval configuration (versioned asset).",
        "# Generated by retrieval.config_io.write_config_yaml; do not edit by hand.",
        "retrieval:",
    ]
    scalar_fields = (
        "bm25_top_k",
        "vector_top_k",
        "fusion_top_k",
        "rerank_top_k",
        "selection_top_k",
        "rrf_k",
        "max_chunks_per_document",
        "max_chunks_per_source",
        "mmr_lambda",
        "evidence_type_bonus",
        "cross_encoder_alpha",
        "freshness_weight_latest_trial",
        "latest_window_days",
        "verified_ratio_freshness_bump",
        "verified_ratio_max",
        "index_version",
        "corpus_version",
        "rerank_config_version",
    )
    for name in scalar_fields:
        lines.append(f"  {name}: {_scalar(getattr(config, name))}")
    lines.append("  source_quality_table:")
    for source, score in config.source_quality_table:
        lines.append(f"    - [{_scalar(source)}, {_scalar(score)}]")
    lines.append("  verified_ratio_base:")
    for question_type, ratio in config.verified_ratio_base:
        lines.append(f"    - [{_scalar(question_type)}, {_scalar(ratio)}]")
    lines.append("  feature_weights:")
    for name in ("semantic", "lexical", "pico_match", "evidence_level", "freshness", "source_reliability"):
        lines.append(f"    {name}: {_scalar(getattr(config.feature_weights, name))}")
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return destination


def load_config_yaml(path: str | Path) -> RetrievalConfig:
    """Strictly parse the frozen YAML and return a validated RetrievalConfig."""
    document = _parse_yaml_subset(Path(path))
    if set(document) != {"retrieval"} or not isinstance(document["retrieval"], dict):
        raise ConfigYamlError("config YAML must contain a single top-level 'retrieval' mapping")
    data = document["retrieval"]
    allowed = {field.name for field in fields(RetrievalConfig)} | {"feature_weights", "source_quality_table"}
    unknown = sorted(set(data) - allowed)
    if unknown:
        raise ConfigYamlError(f"config YAML contains unknown keys: {', '.join(unknown)}")

    weights_data = data.get("feature_weights", {})
    if not isinstance(weights_data, dict) or set(weights_data) != {
        "semantic", "lexical", "pico_match", "evidence_level", "freshness", "source_reliability",
    }:
        raise ConfigYamlError("config YAML feature_weights must list all six weights")
    weights = FeatureWeights(
        semantic=_number(weights_data["semantic"], "semantic"),
        lexical=_number(weights_data["lexical"], "lexical"),
        pico_match=_number(weights_data["pico_match"], "pico_match"),
        evidence_level=_number(weights_data["evidence_level"], "evidence_level"),
        freshness=_number(weights_data["freshness"], "freshness"),
        source_reliability=_number(weights_data["source_reliability"], "source_reliability"),
    )

    table_data = data.get("source_quality_table")
    if not isinstance(table_data, list) or any(
        not isinstance(pair, (list, tuple)) or len(pair) != 2 or not isinstance(pair[0], str) or not _is_number(pair[1])
        for pair in table_data
    ):
        raise ConfigYamlError("config YAML source_quality_table must be a list of [source, score] pairs")
    table = tuple((pair[0], float(pair[1])) for pair in table_data)

    ratio_data = data.get("verified_ratio_base")
    if not isinstance(ratio_data, list) or any(
        not isinstance(pair, (list, tuple)) or len(pair) != 2 or not isinstance(pair[0], str) or not _is_number(pair[1])
        for pair in ratio_data
    ):
        raise ConfigYamlError("config YAML verified_ratio_base must be a list of [question_type, ratio] pairs")
    verified_ratio_base = tuple((pair[0], float(pair[1])) for pair in ratio_data)

    kwargs: dict[str, Any] = {
        "feature_weights": weights,
        "source_quality_table": table,
        "verified_ratio_base": verified_ratio_base,
    }
    for name in (
        "bm25_top_k", "vector_top_k", "fusion_top_k", "rerank_top_k", "selection_top_k",
        "rrf_k", "max_chunks_per_document", "max_chunks_per_source", "mmr_lambda",
        "evidence_type_bonus", "cross_encoder_alpha", "freshness_weight_latest_trial",
        "latest_window_days", "verified_ratio_freshness_bump", "verified_ratio_max",
        "index_version", "corpus_version", "rerank_config_version",
    ):
        if name not in data:
            raise ConfigYamlError(f"config YAML is missing required key: {name}")
        kwargs[name] = data[name]
    try:
        return RetrievalConfig(**kwargs)
    except (TypeError, ValueError) as error:
        raise ConfigYamlError(f"config YAML is not a valid RetrievalConfig: {error}") from error


def config_matches_yaml(config: RetrievalConfig, path: str | Path) -> bool:
    """Return whether ``config`` exactly equals the frozen YAML copy.

    Any drift in K limits, weights, MMR parameters, or version strings means
    the in-code config is not the frozen one (4.3 冻结配置).
    """
    if not isinstance(config, RetrievalConfig):
        return False
    try:
        recorded = load_config_yaml(path)
    except (OSError, ConfigYamlError):
        return False
    return _same_config(config, recorded)


def _same_config(left: RetrievalConfig, right: RetrievalConfig) -> bool:
    weights_left = left.feature_weights
    weights_right = right.feature_weights
    return (
        left.bm25_top_k == right.bm25_top_k
        and left.vector_top_k == right.vector_top_k
        and left.fusion_top_k == right.fusion_top_k
        and left.rerank_top_k == right.rerank_top_k
        and left.selection_top_k == right.selection_top_k
        and left.rrf_k == right.rrf_k
        and left.max_chunks_per_document == right.max_chunks_per_document
        and left.max_chunks_per_source == right.max_chunks_per_source
        and left.mmr_lambda == right.mmr_lambda
        and left.evidence_type_bonus == right.evidence_type_bonus
        and left.cross_encoder_alpha == right.cross_encoder_alpha
        and left.freshness_weight_latest_trial == right.freshness_weight_latest_trial
        and left.latest_window_days == right.latest_window_days
        and left.source_quality_table == right.source_quality_table
        and left.verified_ratio_base == right.verified_ratio_base
        and left.verified_ratio_freshness_bump == right.verified_ratio_freshness_bump
        and left.verified_ratio_max == right.verified_ratio_max
        and left.index_version == right.index_version
        and left.corpus_version == right.corpus_version
        and left.rerank_config_version == right.rerank_config_version
        and weights_left.semantic == weights_right.semantic
        and weights_left.lexical == weights_right.lexical
        and weights_left.pico_match == weights_right.pico_match
        and weights_left.evidence_level == weights_right.evidence_level
        and weights_left.freshness == weights_right.freshness
        and weights_left.source_reliability == weights_right.source_reliability
    )


# --- strict YAML-subset parser -------------------------------------------------

def _parse_yaml_subset(path: Path) -> dict[str, Any]:
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as error:
        raise ConfigYamlError(f"cannot read config YAML: {error}") from error
    lines: list[tuple[int, int, str]] = []
    for line_number, line in enumerate(raw.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        if indent % 2 != 0:
            raise ConfigYamlError(f"line {line_number}: indentation must be a multiple of two")
        lines.append((line_number, indent, stripped))
    if not lines:
        raise ConfigYamlError("config YAML is empty")

    root: dict[str, Any] = {}
    stack: list[tuple[int, dict[str, Any] | list[Any]]] = [(-1, root)]
    for index, (line_number, indent, content) in enumerate(lines):
        while stack and indent <= stack[-1][0]:
            stack.pop()
        if not stack:
            raise ConfigYamlError(f"line {line_number}: inconsistent indentation")
        container = stack[-1][1]
        if content.startswith("- "):
            item = _parse_scalar_line(content[2:], line_number)
            if not isinstance(container, list):
                raise ConfigYamlError(f"line {line_number}: sequence item outside a sequence")
            container.append(item)
            continue
        if ":" not in content:
            raise ConfigYamlError(f"line {line_number}: expected 'key: value'")
        key, _, remainder = content.partition(":")
        key = key.strip()
        if not key:
            raise ConfigYamlError(f"line {line_number}: empty mapping key")
        if isinstance(container, list):
            raise ConfigYamlError(f"line {line_number}: mapping key inside a sequence")
        remainder = remainder.strip()
        if remainder == "":
            child: dict[str, Any] | list[Any] = {} if _next_is_mapping(lines, index, indent) else []
            container[key] = child
            stack.append((indent, child))
        else:
            container[key] = _parse_scalar_line(remainder, line_number)
    return root


def _next_is_mapping(lines: list[tuple[int, int, str]], index: int, current: int) -> bool:
    # Look ahead to the next line at a deeper indent: a mapping has a "key:"
    # line, a sequence has "- " lines.
    for _, indent, content in lines[index + 1 :]:
        if indent <= current:
            break
        if content.startswith("- "):
            return False
        if ":" in content:
            return True
    return False


def _parse_scalar_line(content: str, line_number: int) -> Any:
    if content.startswith("[") and content.endswith("]"):
        inner = content[1:-1].strip()
        if not inner:
            return []
        return [_scalar_item(part.strip(), line_number) for part in _split_flow(inner)]
    return _scalar_item(content, line_number)


def _split_flow(inner: str) -> list[str]:
    parts: list[str] = []
    current: list[str] = []
    for character in inner:
        if character == ",":
            parts.append("".join(current))
            current = []
        else:
            current.append(character)
    parts.append("".join(current))
    return parts


def _scalar_item(text: str, line_number: int) -> Any:
    if not text:
        raise ConfigYamlError(f"line {line_number}: empty flow item")
    return _parse_scalar(text)


def _scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if value is None:
        return "null"
    return str(value)


def _parse_scalar(text: str) -> Any:
    lowered = text.casefold()
    if lowered in {"true", "false"}:
        return lowered == "true"
    if lowered == "null":
        return None
    if _is_int(text):
        return int(text)
    if _is_number(text):
        return float(text)
    return text


def _is_int(text: str) -> bool:
    if not text or (text[0] in "+-" and not text[1:].isdigit()):
        return False
    return text.lstrip("+-").isdigit()


def _is_number(text: str) -> bool:
    try:
        float(text)
        return True
    except ValueError:
        return False


def _number(value: Any, field_name: str) -> float:
    if not _is_number(value):
        raise ConfigYamlError(f"config YAML {field_name} must be a number")
    return float(value)
